project:
  type: website
  render:
   - "*.qmd"
   - "!lecture*"
  output-dir: docs
  post-render:
  - cp -r teaching/monash-wcd/ docs/teaching/monash-wcd/
  - cp -r teaching/monash-cwd/ docs/teaching/monash-cwd/
  - cp -r teaching/monash-eda/ docs/teaching/monash-eda/
  - cp -r teaching/monash-iml/ docs/teaching/monash-iml/

website:
  title: "emi tanaka"
  site-url: https://emitanaka.org
  favicon: images/avatar.png
  description: |
    Emi Tanaka's website and blog that mainly features about
    statistics, data science, R and academia.
  google-analytics: "G-07SZXPNSJZ"
  search: true
  navbar:
    background: primary
    foreground: secondary
    logo: "images/avatar.png"
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Research
        href: research/index.qmd
      - text: Teaching
        href: teaching/index.qmd
      - talks/index.qmd
      - blog/index.qmd
      - about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/statsgen
      - icon: rss
        href: blog.xml
  page-footer:
    left: |
      <b>Dr. Emi Tanaka</b> <br>
      Senior Lecturer in Statistics<br>
      Monash University, Australia<br>
      © Copyright 2021-2023 Emi Tanaka
    right: |
      <i class="fab fa-twitter"></i> <a href="https://twitter.com/statsgen">@statsgen</a> on Twitter <br>
      <i class="fab fa-github"></i> <a href="https://github.com/emitanaka">emitanaka</a> on GitHub <br>
      <i class="fas fa-envelope"></i> <a href="mailto:emi.tanaka@monash.edu">emi.tanaka@monash.edu</a><br>
      <i class="fas fa-map-marker-alt"></i> Clayton, Victoria, Australia
    border: true
    background: primary
format:
  html:
    theme: assets/theme.scss
    css: assets/styles.css
    include-after: |
      <link rel="stylesheet" href="/assets/syntax-highlight.css">
      <link rel="stylesheet" href="/assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="/assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>


