---
title: "War"
description: |
  What good is in a war?
date: 2022-03-06
author:
  - name: Emi Tanaka
    url: https://emitanaka.org
    affiliation: Monash University
    affiliation_url: https://numbat.space/
categories: [life]
---


The war that's going on at Ukraine is terrible. There are now [over 1.3 million people who have fled Ukraine since the Russian invasion](https://www.theguardian.com/global-development/2022/mar/05/ukraine-un-says-more-than-13-million-have-fled-since-russian-invasion-began), many who would be living as refugees now in neighboring countries. The closest to war I have ever been is when the Japanese embassy told (warned?) my family to get out of Jordan during the Gulf War. We lived in Greece during this period. 

When I lived in Greece, I was a young child with little comprehension of what's going on. In the course of my life, this event had little effect on me but just a distant hazy memory. Today as a fully grown adult, I'm sure I would have been terrified being in the midst of uncertainty. War affects many citizens, including the creator of [Leaflet](https://leafletjs.com/) as pointed out by [Hiroaki Yutani-san](https://twitter.com/yutannihilat_en/status/1497938887272189952). If ever you need a time to remind yourself how lucky you are to have shelter, food and water, now is probably the time. 

Living in Melbourne, so far away from Ukraine, life is going on like normal, bickering over first world problems. What good is in a war? If you are in a good position to, please consider helping those in need. I donated US$500 to Ukraine Red Cross Society but I found later that there was the [Ukraine Crisis Appeal in the Australian Red Cross](https://www.redcross.org.au/ukraine/). 


